name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    container: nixos/nix:2.3.6
    steps:
      - uses: actions/checkout@v2
      - run: nix-build
